### PR TITLE
use env local dev prod

### PR DESCRIPTION
**Pull request by TylerWanner**

### CODE REVIEW

**Review by felimadu — APPROVED** [review]
Do we want to start support sepolia?

**Comment by felimadu** [comment]
Also, given that chains usually do `testnet` and `mainnet`, do we want to add comments on what is prod vs dev vs local?

**Comment by TylerWanner** [comment]
> Also, given that chains usually do `testnet` and `mainnet`, do we want to add comments on what is prod vs dev vs local?

I don't understand this question @felimadu

**Comment by TylerWanner** [comment]
> Do we want to start support sepolia?

yes, updating from goerli to sepolia is on the list of things to do
i don't think we should support goerli

**Pull request merged**
